[package]
name = "cofiblocks-interfaces"
description = "Tipos e interfaces compartidas entre los contratos de CofiBlocks"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
