
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Use DIRECT_URL for migrations (port 5432), fallback to DATABASE_URL
    // Migrations require a direct connection, not a pooled connection
    url: env("DIRECT_URL") || env("DATABASE_URL"),
  },
});
